language: python

stages:
  - tests-pylint
  - tests-pytest

jobs:
  include:
    - stage: static-analysis
      python: 3.6
      env: TOXENV=static_analysis
    - stage: unittests
      python: 3.6
      env: TOXENV=unittests

before_install:
  - python --version
  - uname -a

install:
  - pip install -U setuptools
  - pip install tox
  - virtualenv --version
  - pip --version
  - tox --version

script:
  # Test install with current version of setuptools
  - pip install .
  - tox
