"""API routes"""

ROUTE_AGENTS = "/api/v3/agents"
ROUTE_CVE_ANNOUNCEMENTS = "/api/v3/cve_announcements"
ROUTE_GROUPS = "/api/v3/groups"
ROUTE_HOSTS = "/api/v3/hosts"
ROUTE_IMPORTER = "/api/v2/cbw_scans/scripts"
ROUTE_NODES = "/api/v3/nodes"
ROUTE_PING = "/api/v3/ping"
ROUTE_REMOTE_ACCESSES = "/api/v3/remote_accesses"
ROUTE_SECURITY_ISSUES = "/api/v3/security_issues"
ROUTE_SERVERS = "/api/v3/servers"
ROUTE_USERS = "/api/v3/users"
