"""API routes"""

ROUTE_AGENTS = "/api/v3/assets/agents"
ROUTE_ASSETS = "/api/v3/assets/servers"
ROUTE_APPLICATIVE_SCANS = "/api/v3/assets/applicative_scans"
ROUTE_COMPLIANCE_ASSETS = "/api/v3/compliance/servers"
ROUTE_COMPLIANCE_RULES = "/api/v3/compliance/rules"
ROUTE_CVE_ANNOUNCEMENTS = "/api/v3/vulnerabilities/cve_announcements"
ROUTE_DISCOVERY = "/api/v3/assets/discoveries"
ROUTE_DOCKER_IMAGES = "/api/v3/assets/docker_images"
ROUTE_GROUPS = "/api/v3/assets/groups"
ROUTE_HOSTS = "/api/v3/hosts"
ROUTE_AIRGAPPED_SCRIPTS = "/api/v2/cbw_scans/scripts"
ROUTE_AIRGAPPED_COMPLIANCE_SCRIPTS = "/api/v2/compliances/scripts"
ROUTE_NODES = "/api/v3/nodes"
ROUTE_PING = "/api/v3/ping"
ROUTE_REMOTE_ACCESSES = "/api/v3/assets/remote_accesses"
ROUTE_SECURITY_ISSUES = "/api/v3/vulnerabilities/security_issues"
ROUTE_SERVERS = "/api/v3/vulnerabilities/servers"
ROUTE_STORED_CREDENTIALS = "/api/v3/assets/credentials"
ROUTE_USERS = "/api/v3/users"
ROUTE_OS = "/api/v3/os"
