name: Main Workflow
on: [push, pull_request]

jobs:
  code_style:
    name: Code Style Analysis
    runs-on: ubuntu-latest
    env:
      TOXENV: static_analysis
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          pip install -U setuptools
          pip install tox
          virtualenv --version
          pip --version
          tox --version
      - name: Test install with current version of setuptools
        run: |
          pip install .
          tox
  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    env:
      TOXENV: unittests
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Install dependencies
        run: |
          pip install -U setuptools
          pip install tox
          virtualenv --version
          pip --version
          tox --version
      - name: Test install with current version of setuptools
        run: |
          pip install .
          tox
